model_path:
  small: "./models/llama2-chat-7b-q4"
  large: "./models/llama2-chat-7b-q4"

model_type: "mistral"

embeddings_path: "BAAI/bge-large-en-v1.5"

model_config: 
  'max_new_tokens': 512
  'temperature' : 0.7
  'context_length': 4096
  'gpu_layers' : 0

chat_history_path: "./chat_sessions/"